# This is the default toml config file that is used by the rest API server.
#
[solr]
hostname = "localhost"
port = 8983
core = "files"

[mongo_db]
hostname = "localhost"
port = 27017
user = "mongo"
password = "secret"
name = "search_stats"
