# This is the default toml config file that is used by the rest API server.
#
[restAPI]
services = ["databrowser", "zarr-stream"]
url = "http://localhost:7777"

[solr]
hostname = "localhost"
port = 8983
core = "files"

[mongo_db]
hostname = "localhost"
port = 27017
user = "mongo"
password = "secret"
name = "search_stats"

[cache]
hostname = "localhost"
port = 6379
exp = 3600
user = "redis"
password = "secret"
cert_file = ""
key_file = ""

[oidc]
discovery_url = "http://localhost:8080/realms/freva/.well-known/openid-configuration"
client_id = "freva"
client_secret = ""
