version: "3.9"
services:
  solr:
    networks:
      - freva-rest
    image: docker.io/solr:latest
    environment:
      CORE: files
    ports:
      - "8983:8983"
    volumes:
      - ./config/solr/managed-schema.xml:/opt/solr/managed-schema.xml:ro
      - ./config/solr/synonyms.txt:/opt/solr/synonyms.txt:ro
      - ./create_cores.sh:/docker-entrypoint-initdb.d/create_cores.sh:ro
    hostname: solr
  redis:
    networks:
      - freva-rest
    image: docker.io/redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_USERNAME: redis
      REDIS_PASSWORD: secret
      REDIS_LOGLEVEL: debug
      REDIS_SSL_CERTFILE: /certs/client-cert.pem
      REDIS_SSL_KEYFILE: /certs/client-key.pem
    hostname: redis
    volumes:
      - ./config/redis/redis-cmd.sh:/usr/local/bin/redis-cmd
      - ./config/certs:/certs
    command: /usr/local/bin/redis-cmd
  keycloak:
    networks:
      - freva-rest
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      JAVA_OPTS_APPEND: "-Djava.net.preferIPv4Stack=true"
    hostname: keycloak
    volumes:
      - ./config/certs:/certs
      - ./config/keycloak/import:/opt/keycloak/data/import:z
    ports:
      - "8080:8080"
      - "8443:8443"
    command: |
      start-dev
      --hostname-strict=false
      --import-realm
      -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
  ldap:
    image: docker.io/osixia/openldap:latest
    environment:
      LDAP_ORGANISATION: "My Organization"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin_password"
      LDAP_ADMIN_USERNAME: "admin"
    ports:
      - "389:389"
      - "636:636"
    command: --copy-service
    hostname: ldap
    networks:
      - freva-rest
    volumes:
      - ./config/keycloak/users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/users.ldif
  mongodb:
    networks:
      - freva-rest
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: search_stats
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./config/mongo/mongo-userdata-init.js:/docker-entrypoint-initdb.d/mongo-userdata-init.js:ro

  stac-api:
    networks:
      - freva-rest
    image: ghcr.io/mo-dkrz/stac-fastapi-es:v2.2.9
    environment:
      - RUN_LOCAL_ES=1
      - STAC_FASTAPI_TITLE=Freva STAC Service
      - STAC_FASTAPI_DESCRIPTION=`Freva STAC Service` provides a SpatioTemporal Asset Catalog (STAC) API implementation geospatial data cataloging and discovery.
      - STAC_FASTAPI_ROUTE_DEPENDENCIES=[{"routes":[{"path":"/collections/{collection_id}/items/{item_id}","method":["PUT","DELETE"]},{"path":"/collections/{collection_id}/items","method":["POST"]},{"path":"/collections","method":["POST"]},{"path":"/collections/{collection_id}","method":["PUT","DELETE"]},{"path":"/collections/{collection_id}/bulk_items","method":["POST"]},{"path":"/aggregations","method":["POST"]},{"path":"/collections/{collection_id}/aggregations","method":["POST"]},{"path":"/aggregate","method":["POST"]},{"path":"/aggregate","method":["POST"]},{"path":"/collections/{collection_id}/aggregate","method":["POST"]}],"dependencies":[{"method":"stac_fastapi.core.basic_auth.BasicAuth","kwargs":{"credentials":[{"username":"stac","password":"secret"}]}}]}]
      - STAC_USERNAME=stac
      - STAC_PASSWORD=secret
    ports:
      - "8083:8080"
      - "9200:9200"

  stac-browser:
    networks:
      - freva-rest
    image: ghcr.io/radiantearth/stac-browser:latest
    environment:
      - SB_catalogUrl=http://localhost:8083
      - SB_catalogTitle=Freva STAC Service
    ports:
      - "8084:8080"
    depends_on:
      - stac-api

networks:
  freva-rest:
    driver: bridge
