# this is a test configuration toml file used to debug the parameter parser

[input_parameters]

[input_parameters.date]
type = "Date"
help = "Enter a date"
default = "2020-01-01"
mandatory = true

[input_parameters.string]
type = "String"
default = "hello"

[input_parameters.experiment]
facet = "experiment"
type = "DataField"
default = "era5"

[input_parameters.range]
default = [1,2,3,4,5]
type = "Range"

[input_parameters.file]
default = "./input_params.toml"
type = "File"



